# Generated by Django 4.2.11 on 2024-05-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShoppee', '0005_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product', to='appShoppee.categories'),
        ),
    ]
